### ISSUE TITLE
Title head for LC

### ISSUE THREAD

**Issue by rsameera99** [Farazkhan0516/Lung-Cancer-Prediction-using-Machine-Learning#1]
Hello. Thank you for sharing this repository and it is very helpful for me to try for machine learning. I have a question, the title in LC file, like

TP53 | PTEN | EGFR | KRAS | FGFR1 | ALK | METex14 | MET | BRAF | PIK3CA | ROS1 | HER2 | RET

 what do they stand for?  thank you in advance!

**Comment by Farazkhan0516** [comment]
Hey Thanks for your comment 
these are the names of genes whose mutation is responsible for causing lung cancer in human body.

**Comment by rsameera99** [comment]
I see, thank you very much! Another question, may I know the source of your data? Where can I get the data
